#!/bin/bash

# exit on error
set -e

# source debconf library
#. /usr/share/debconf/confmodule

DIR=/usr/share/simple-signer

# create system-wide venv and install python libraries via pip
python3 -m venv --system-site-packages $DIR/venv
$DIR/venv/bin/pip3 install --upgrade $DIR
$DIR/venv/bin/pip3 uninstall -y pip

# recognize desktop shortcut / protocol handler
sudo update-desktop-database
