#!/bin/bash

# exit on error
set -e

# source debconf library
#. /usr/share/debconf/confmodule

DIR=/usr/share/simple-signer

# remove venv
rm -r $DIR/build || true
rm -r $DIR/simple_signer/__pycache__ || true
rm -r $DIR/venv
rm -r $DIR/simple_signer.egg-info
